/*  
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import EncoderAndDecoder.DeCoder;
import EncoderAndDecoder.EnCoder;
import beanClass.*;
import databaseManager.DatabaseManager;
import java.awt.event.ActionEvent;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.event.*;
/**
 *
 * @author HP
 */
public class Batch extends javax.swing.JFrame implements ListSelectionListener {

    /**
     * Creates new form Batch
     */
    public Batch() {
        try {
            initComponents();
             getFaculty();
             batchShiftListItem.addItem("MORNING");
             batchShiftListItem.addItem("EVENING");
             batchShiftListItem.addItem("NOON");
          
             batchGroupListItem.addItem("MEDICAL");
             batchGroupListItem.addItem("ENGINEERING");
             batchGroupListItem.addItem("COMMERCE");
             batchGroupListItem.addItem("GENERAL");
          
        YearhList.addListSelectionListener(this);
        } catch (Exception ex) {
            
        }
    }
    public void actionPerformed(ActionEvent e){
        if(e.getSource()==batchAddButton)
            addRecord();
        if(e.getSource()==batchAddButton){
        // hide();
         dispose();
         } 
        if(e.getSource()==batchAddButton)
            clear();
    }
     private void clear(){
         
        batchIdTextField.setText("");
        batchYearTextField.setText("");
        batchRemarksTextAria.setText("");
        
    }
     private void addRecord(){
         programBean bean=(programBean)programComboBox.getSelectedItem();
       
         if(bean==null)return;
          
            String batchYear = batchYearTextField.getText();
            String shift = EnCoder.shiftEncode((String)batchShiftListItem.getSelectedItem());
            String group =EnCoder.groupEncode((String) batchGroupListItem.getSelectedItem());
            String remarks = batchRemarksTextAria.getText();
            try{
                int rows=DatabaseManager.addBatch(bean.getProgId(),batchYear,shift,group,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                clear();
                getBatch();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }
      private void updateRecord(){
           programBean bean=(programBean)programComboBox.getSelectedItem();
        batchBean bean1=(batchBean)YearhList.getSelectedValue();
         if(bean1==null)return ;
         try{
         String batchYear = batchYearTextField.getText();
            String shift = EnCoder.shiftEncode((String)batchShiftListItem.getSelectedItem());
            String group =EnCoder.groupEncode((String) batchGroupListItem.getSelectedItem());
            String remarks = batchRemarksTextAria.getText();
            
          int rows=DatabaseManager.updateBatch( bean1.getProgId(),bean1.getBatchId(),batchYear,shift,group,remarks);
            
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"update ");
                clear();
                getBatch();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         }
       private void deleteRecord(){
    batchBean bean = (batchBean)YearhList.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = DatabaseManager.deleteBatch(bean.getBatchId());
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+" Delete ");
                clear();
                   getBatch();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         } 
    public void valueChanged(ListSelectionEvent e){
      
    }//end valueChanged()
    
    
    private void getFaculty(){
        try{
    Vector v  = DatabaseManager.getFaculty();
   facultyComboBox.removeAllItems();
    for(int i=0; i<v.size();  i++ ){ 
        facultyBean bean =(facultyBean)v.elementAt(i);
        facultyComboBox.addItem(bean);
    } 
        }catch(Exception e){
            e.printStackTrace();
    //         JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batchLabel = new javax.swing.JLabel();
        departmentBatchLabel = new javax.swing.JLabel();
        programBatchLabel = new javax.swing.JLabel();
        batchIdLabel = new javax.swing.JLabel();
        batchYearLabel = new javax.swing.JLabel();
        batchYearTextField = new javax.swing.JTextField();
        batchShiftLabel = new javax.swing.JLabel();
        batchRemarksLabel = new javax.swing.JLabel();
        batchShiftListItem = new javax.swing.JComboBox<>();
        batchGroupLabel = new javax.swing.JLabel();
        batchGroupListItem = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        batchRemarksTextAria = new javax.swing.JTextArea();
        batchListLabel = new javax.swing.JLabel();
        batchIdTextField = new javax.swing.JTextField();
        batchAddButton = new javax.swing.JButton();
        batchUpdateButton = new javax.swing.JButton();
        batchDeleteButton = new javax.swing.JButton();
        batchClearButton = new javax.swing.JButton();
        batchBackButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        YearhList = new javax.swing.JList();
        facultyComboBox = new javax.swing.JComboBox();
        departmentComboBox = new javax.swing.JComboBox();
        programComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        batchLabel.setBackground(new java.awt.Color(255, 51, 51));
        batchLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchLabel.setText("BATCH");
        getContentPane().add(batchLabel);
        batchLabel.setBounds(230, 13, 60, 20);

        departmentBatchLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentBatchLabel.setText("DEPARTMENT");
        getContentPane().add(departmentBatchLabel);
        departmentBatchLabel.setBounds(130, 100, 90, 30);

        programBatchLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        programBatchLabel.setText("PROGRAM");
        getContentPane().add(programBatchLabel);
        programBatchLabel.setBounds(150, 140, 70, 30);

        batchIdLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchIdLabel.setText("BATCH ID");
        getContentPane().add(batchIdLabel);
        batchIdLabel.setBounds(160, 260, 60, 30);

        batchYearLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchYearLabel.setText("BATCH YEAR");
        getContentPane().add(batchYearLabel);
        batchYearLabel.setBounds(140, 300, 80, 30);

        batchYearTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchYearTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(batchYearTextField);
        batchYearTextField.setBounds(220, 300, 70, 30);

        batchShiftLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchShiftLabel.setText("SHIFT");
        getContentPane().add(batchShiftLabel);
        batchShiftLabel.setBounds(300, 280, 60, 20);

        batchRemarksLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchRemarksLabel.setText("REMARKS");
        getContentPane().add(batchRemarksLabel);
        batchRemarksLabel.setBounds(220, 370, 70, 30);

        batchShiftListItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(batchShiftListItem);
        batchShiftListItem.setBounds(300, 300, 130, 30);

        batchGroupLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchGroupLabel.setText("GROUP");
        getContentPane().add(batchGroupLabel);
        batchGroupLabel.setBounds(440, 280, 50, 20);

        batchGroupListItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(batchGroupListItem);
        batchGroupListItem.setBounds(440, 300, 170, 30);

        batchRemarksTextAria.setColumns(20);
        batchRemarksTextAria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchRemarksTextAria.setRows(5);
        jScrollPane1.setViewportView(batchRemarksTextAria);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 400, 390, 81);

        batchListLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchListLabel.setText("BATCH YEARS");
        getContentPane().add(batchListLabel);
        batchListLabel.setBounds(620, 40, 110, 20);

        batchIdTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(batchIdTextField);
        batchIdTextField.setBounds(220, 260, 70, 30);

        batchAddButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchAddButton.setText("ADD");
        batchAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchAddButton);
        batchAddButton.setBounds(220, 510, 80, 50);

        batchUpdateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchUpdateButton.setText("UPDATE");
        batchUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchUpdateButton);
        batchUpdateButton.setBounds(310, 510, 90, 50);

        batchDeleteButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchDeleteButton.setText("DELETE");
        batchDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchDeleteButton);
        batchDeleteButton.setBounds(500, 510, 110, 50);

        batchClearButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchClearButton.setText("CLEAR");
        batchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchClearButton);
        batchClearButton.setBounds(410, 510, 80, 50);

        batchBackButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        batchBackButton.setText("BACK");
        batchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchBackButton);
        batchBackButton.setBounds(620, 510, 120, 50);

        YearhList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        YearhList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                YearhListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(YearhList);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(620, 60, 110, 420);

        facultyComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox);
        facultyComboBox.setBounds(220, 60, 390, 30);

        departmentComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(departmentComboBox);
        departmentComboBox.setBounds(220, 100, 390, 30);

        programComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        programComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(programComboBox);
        programComboBox.setBounds(220, 140, 390, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("FACULTY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 60, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batchUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchUpdateButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_batchUpdateButtonActionPerformed

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        // TODO add your handling code here:get
        getDepartment();
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        // TODO add your handling code here:
        getProgram();
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    private void programComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programComboBoxActionPerformed
        // TODO add your handling code here:
        getBatch();
    }//GEN-LAST:event_programComboBoxActionPerformed

    private void YearhListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_YearhListValueChanged
       
       batchBean bean=(batchBean)YearhList.getSelectedValue();
       if(bean==null)return;
       batchShiftListItem.setSelectedItem(DeCoder.shiftDecode(bean.getShift()));
       batchGroupListItem.setSelectedItem(DeCoder.groupDecode(bean.getGroupDesc()));
       batchIdTextField.setText(""+bean.getBatchId());
       batchYearTextField.setText(""+bean.getBatchYear());
       batchRemarksTextAria.setText(""+bean.getRemarks());
    }//GEN-LAST:event_YearhListValueChanged

    private void batchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchBackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batchBackButtonActionPerformed

    private void batchAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchAddButtonActionPerformed
        // TODO add your handling code here:
        addRecord();
    }//GEN-LAST:event_batchAddButtonActionPerformed

    private void batchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchClearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_batchClearButtonActionPerformed

    private void batchYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchYearTextFieldActionPerformed

    private void batchDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchDeleteButtonActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_batchDeleteButtonActionPerformed
    
     private void getBatch(){
            programBean bean=(programBean) programComboBox.getSelectedItem();
            if(bean==null)return;
            try{
            Vector v=DatabaseManager.getBatch(bean.getProgId());
            YearhList.setListData(v);
                    
            }//end try-block
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this," Error : "+e.getMessage());
            }//end  catch
        
        }//end getProgram();
 
     private void getDepartment(){
            facultyBean bean=(facultyBean) facultyComboBox.getSelectedItem();
            if(bean==null) return;
            try{
                departmentComboBox.removeAllItems();
                 Vector v=DatabaseManager.getDepartment(bean.getFacId());

            for(int i=0;i<v.size();i++){
                departmentBean bean1=(departmentBean)v.elementAt(i);
                departmentComboBox.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
        }
        
             private void getProgram(){
            departmentBean bean=(departmentBean) departmentComboBox.getSelectedItem();
            if(bean==null) return;
            try{
                programComboBox.removeAllItems();
                 Vector v=DatabaseManager.getProgram(bean.getDeptId());
            
            for(int i=0;i<v.size();i++){
                programBean bean1=(programBean)v.elementAt(i);
                programComboBox.addItem(bean1);
               
            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
    
        }
              
                    
      
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList YearhList;
    private javax.swing.JButton batchAddButton;
    private javax.swing.JButton batchBackButton;
    private javax.swing.JButton batchClearButton;
    private javax.swing.JButton batchDeleteButton;
    private javax.swing.JLabel batchGroupLabel;
    private javax.swing.JComboBox batchGroupListItem;
    private javax.swing.JLabel batchIdLabel;
    private javax.swing.JTextField batchIdTextField;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JLabel batchListLabel;
    private javax.swing.JLabel batchRemarksLabel;
    private javax.swing.JTextArea batchRemarksTextAria;
    private javax.swing.JLabel batchShiftLabel;
    private javax.swing.JComboBox<String> batchShiftListItem;
    private javax.swing.JButton batchUpdateButton;
    private javax.swing.JLabel batchYearLabel;
    private javax.swing.JTextField batchYearTextField;
    private javax.swing.JLabel departmentBatchLabel;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel programBatchLabel;
    private javax.swing.JComboBox programComboBox;
    // End of variables declaration//GEN-END:variables
}
