/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import beanClass.*;
import  databaseManager.*;
import java.awt.event.ActionEvent;
import java.util.Vector;
import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Department extends javax.swing.JFrame {

    /**
     * Creates new form Department
     */
    public Department() {
         
          initComponents();
            getFaculty();
             
       
    }
     public void actionPerformed(ActionEvent e){
        if(e.getSource()==departmetAddButton)
            addRecord();
        if(e.getSource()==departmetAddButton){
        // hide();
         dispose();
         } 
        if(e.getSource()==departmetAddButton)
            clear();
    }
     private void clear(){
         //facultyComboBox.setItem("");
        departmentIdTextField.setText("");
        departmenNameTextField.setText("");
        departmenRemarksTextArea.setText("");
        
    }
     private void addRecord(){
         facultyBean bean=(facultyBean)facultyComboBox.getSelectedItem();
         if(bean==null)return;
            String  deptName = departmenNameTextField.getText();
            String remarks = departmenRemarksTextArea.getText();
            try{
                int rows=DatabaseManager.addDepartment(bean.getFacId(),deptName,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                clear();
                getDepartment();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }
      private void updateRecord(){
         departmentBean bean=(departmentBean)departmentsList.getSelectedValue();
         if(bean==null)return ;
         try{
          int rows=DatabaseManager.updateDepartment( bean.getFacId(),bean.getDeptId(),departmenNameTextField.getText(),departmenRemarksTextArea.getText());
            
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"update ");
                clear();
                
                getDepartment();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         }
      private void deleteRecord(){
    departmentBean bean = (departmentBean)departmentsList.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = DatabaseManager.deleteDepartment(bean.getDeptId());
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+" Delete ");
                clear();
                getDepartment();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         } 
    private void getFaculty(){
        try{
    Vector v  = DatabaseManager.getFaculty();
   facultyComboBox.removeAllItems();
    for(int i=0; i<v.size();  i++ ){ 
        facultyBean bean =(facultyBean)v.elementAt(i);
        facultyComboBox.addItem(bean);
    } 
        }catch(Exception e){
            e.printStackTrace();
    //         JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
        }
        }
        
       private void getDepartment(){
           facultyBean bean = (facultyBean)facultyComboBox.getSelectedItem();
           if(bean==null)return;
           try{
               Vector v = DatabaseManager.getDepartment(bean.getFacId());
               departmentsList.setListData(v);
           }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
           }
       } 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        departmentLabel = new javax.swing.JLabel();
        dpartmentFacultyLabel = new javax.swing.JLabel();
        departmentIdLabel = new javax.swing.JLabel();
        departmenNameLabel = new javax.swing.JLabel();
        departmenRemarksLabel = new javax.swing.JLabel();
        departmentIdTextField = new javax.swing.JTextField();
        departmenNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmenRemarksTextArea = new javax.swing.JTextArea();
        departmntsLabel = new javax.swing.JLabel();
        departmetAddButton = new javax.swing.JButton();
        departmetUpdateButton = new javax.swing.JButton();
        departmetDeleteButton = new javax.swing.JButton();
        departmetClearButton = new javax.swing.JButton();
        departmeBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        departmentsList = new javax.swing.JList();
        facultyComboBox = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(760, 500));
        getContentPane().setLayout(null);

        departmentLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentLabel.setText("DEPARTMENT");
        getContentPane().add(departmentLabel);
        departmentLabel.setBounds(280, 10, 140, 40);

        dpartmentFacultyLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dpartmentFacultyLabel.setText("FACULTY");
        getContentPane().add(dpartmentFacultyLabel);
        dpartmentFacultyLabel.setBounds(90, 70, 60, 40);

        departmentIdLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentIdLabel.setText("DEPARTMENT ID");
        getContentPane().add(departmentIdLabel);
        departmentIdLabel.setBounds(50, 150, 100, 40);

        departmenNameLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmenNameLabel.setText("DEPARTMENT NAME");
        getContentPane().add(departmenNameLabel);
        departmenNameLabel.setBounds(30, 200, 120, 40);

        departmenRemarksLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmenRemarksLabel.setText("REMARKS");
        getContentPane().add(departmenRemarksLabel);
        departmenRemarksLabel.setBounds(160, 260, 70, 20);

        departmentIdTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(departmentIdTextField);
        departmentIdTextField.setBounds(160, 150, 60, 40);

        departmenNameTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(departmenNameTextField);
        departmenNameTextField.setBounds(160, 200, 300, 40);

        departmenRemarksTextArea.setColumns(20);
        departmenRemarksTextArea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmenRemarksTextArea.setRows(5);
        jScrollPane1.setViewportView(departmenRemarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 280, 300, 120);

        departmntsLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmntsLabel.setText("DEPARTMENTS");
        getContentPane().add(departmntsLabel);
        departmntsLabel.setBounds(474, 45, 90, 20);

        departmetAddButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmetAddButton.setText("ADD");
        departmetAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmetAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmetAddButton);
        departmetAddButton.setBounds(160, 410, 80, 30);

        departmetUpdateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmetUpdateButton.setText("UPDATE");
        departmetUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmetUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmetUpdateButton);
        departmetUpdateButton.setBounds(260, 410, 79, 30);

        departmetDeleteButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmetDeleteButton.setText("DELETE");
        departmetDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmetDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmetDeleteButton);
        departmetDeleteButton.setBounds(470, 410, 110, 30);

        departmetClearButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmetClearButton.setText("CLEAR");
        departmetClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmetClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmetClearButton);
        departmetClearButton.setBounds(360, 410, 80, 30);

        departmeBackButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmeBackButton.setText("BACK");
        departmeBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmeBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmeBackButton);
        departmeBackButton.setBounds(590, 410, 120, 30);

        departmentsList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        departmentsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                departmentsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(departmentsList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(470, 70, 240, 330);

        facultyComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox);
        facultyComboBox.setBounds(160, 70, 300, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmetUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmetUpdateButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_departmetUpdateButtonActionPerformed

   
    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        // TODO add your handling code here:
       
                 getDepartment();
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void departmentsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_departmentsListValueChanged
        // TODO add your handling code here:
        departmentBean bean =(departmentBean)departmentsList.getSelectedValue();
        if(bean==null)return;{
        departmentIdTextField.setText(""+bean.getDeptId());
        departmenNameTextField.setText(""+bean.getDeptName());
        departmenRemarksTextArea.setText(""+bean.getRemarks());
    }
    }//GEN-LAST:event_departmentsListValueChanged

    private void departmeBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmeBackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_departmeBackButtonActionPerformed

    private void departmentIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentIdTextFieldActionPerformed

    private void departmetClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmetClearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_departmetClearButtonActionPerformed

    private void departmetAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmetAddButtonActionPerformed
        // TODO a(dd your handling code here:
        addRecord();
    }//GEN-LAST:event_departmetAddButtonActionPerformed

    private void departmetDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmetDeleteButtonActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_departmetDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton departmeBackButton;
    private javax.swing.JLabel departmenNameLabel;
    private javax.swing.JTextField departmenNameTextField;
    private javax.swing.JLabel departmenRemarksLabel;
    private javax.swing.JTextArea departmenRemarksTextArea;
    private javax.swing.JLabel departmentIdLabel;
    private javax.swing.JTextField departmentIdTextField;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JList departmentsList;
    private javax.swing.JButton departmetAddButton;
    private javax.swing.JButton departmetClearButton;
    private javax.swing.JButton departmetDeleteButton;
    private javax.swing.JButton departmetUpdateButton;
    private javax.swing.JLabel departmntsLabel;
    private javax.swing.JLabel dpartmentFacultyLabel;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

  
}
