 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;


import beanClass.facultyBean;
import databaseManager.DatabaseManager;
import java.awt.event.ActionEvent;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.event.*;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author HP
 */
public class Faculty extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form Faculty
     */
    public Faculty() {
        initComponents();
          try {
            getFaculty();
            facultyList.addListSelectionListener(this);
        } catch (Exception ex) {
           
        }
    }
    public void actionPerformed(ActionEvent e){
        if(e.getSource()==facultyAddButton)
            addRecord();
        if(e.getSource()==facultyBackButton){
         hide();
        // dispose();
         } 
        if(e.getSource()==facultyClearButton)
            clear();
    }
    private void clear(){
        facultyIdTextField.setText("");
        facultyNameTextField.setText("");
        facultyRemarksTextAria.setText("");
        
    }
    private void addRecord(){
            String  facName = facultyNameTextField.getText();
            String remarks = facultyRemarksTextAria.getText();
            try{
                int rows=DatabaseManager.addFaculty(facName,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                clear();
                getFaculty();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }
    private void updateRecord(){
         facultyBean bean=(facultyBean)facultyList.getSelectedValue();
         if(bean==null)return ;
         try{
          int rows=DatabaseManager.updateFaculty(bean.getFacId(),facultyNameTextField.getText(),facultyRemarksTextAria.getText());
            
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                clear();
                getFaculty();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         }
     
    private void deleteRecord(){
    facultyBean bean = (facultyBean)facultyList.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = DatabaseManager.deleteFaculty(bean.getFacId());
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+" Delete ");
                clear();
                getFaculty();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         } 
    
    

    
    public void valueChanged(ListSelectionEvent e){
       facultyBean bean=(facultyBean)facultyList.getSelectedValue();
       if(bean==null)return;
       facultyIdTextField.setText(""+bean.getFacId());
       facultyNameTextField.setText(bean.getFacName());
       facultyRemarksTextAria.setText(bean.getRemarks());
    }
    private void getFaculty(){
    try{
        Vector v=DatabaseManager.getFaculty();
        facultyList.setListData(v);
    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    }
    }              
   
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        facultyLabel = new javax.swing.JLabel();
        facultyIdLabael = new javax.swing.JLabel();
        facultyNameLabel = new javax.swing.JLabel();
        facultyRemarksLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facultyRemarksTextAria = new javax.swing.JTextArea();
        facultyNameTextField = new javax.swing.JTextField();
        facultyAddButton = new javax.swing.JButton();
        facultyUpdateButton = new javax.swing.JButton();
        facultyDeleteButton = new javax.swing.JButton();
        facultyClearButton = new javax.swing.JButton();
        facultyBackButton = new javax.swing.JButton();
        facultiesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        facultyList = new javax.swing.JList();
        facultyIdTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        setTitle("FACULTY");
        setBackground(new java.awt.Color(153, 0, 153));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(750, 425));
        getContentPane().setLayout(null);

        facultyLabel.setBackground(new java.awt.Color(255, 255, 255));
        facultyLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyLabel.setForeground(new java.awt.Color(0, 51, 51));
        facultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facultyLabel.setText("FACULTY");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(280, 10, 170, 60);

        facultyIdLabael.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyIdLabael.setText("FACULTY ID");
        getContentPane().add(facultyIdLabael);
        facultyIdLabael.setBounds(60, 80, 110, 22);

        facultyNameLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyNameLabel.setText("FACULTY NAME");
        getContentPane().add(facultyNameLabel);
        facultyNameLabel.setBounds(40, 130, 130, 15);

        facultyRemarksLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyRemarksLabel.setText("REMARKS");
        getContentPane().add(facultyRemarksLabel);
        facultyRemarksLabel.setBounds(130, 170, 60, 15);

        facultyRemarksTextAria.setColumns(20);
        facultyRemarksTextAria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyRemarksTextAria.setRows(5);
        jScrollPane1.setViewportView(facultyRemarksTextAria);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 280, 100);

        facultyNameTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(facultyNameTextField);
        facultyNameTextField.setBounds(130, 120, 280, 40);

        facultyAddButton.setBackground(new java.awt.Color(0, 153, 153));
        facultyAddButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyAddButton.setText("ADD");
        facultyAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyAddButton);
        facultyAddButton.setBounds(130, 340, 80, 30);

        facultyUpdateButton.setBackground(new java.awt.Color(0, 153, 153));
        facultyUpdateButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyUpdateButton.setText("UPDATE");
        facultyUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyUpdateButton);
        facultyUpdateButton.setBounds(240, 340, 79, 30);

        facultyDeleteButton.setBackground(new java.awt.Color(0, 153, 153));
        facultyDeleteButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyDeleteButton.setText("DELETE");
        facultyDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyDeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyDeleteButton);
        facultyDeleteButton.setBounds(460, 340, 120, 30);

        facultyClearButton.setBackground(new java.awt.Color(0, 153, 153));
        facultyClearButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyClearButton.setText("CLEAR");
        facultyClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyClearButton);
        facultyClearButton.setBounds(350, 340, 80, 30);

        facultyBackButton.setBackground(new java.awt.Color(0, 153, 153));
        facultyBackButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultyBackButton.setText("BACK");
        facultyBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyBackButton);
        facultyBackButton.setBounds(600, 340, 110, 30);

        facultiesLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        facultiesLabel.setText("FACULTIES");
        getContentPane().add(facultiesLabel);
        facultiesLabel.setBounds(480, 50, 90, 15);

        facultyList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jScrollPane3.setViewportView(facultyList);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(420, 70, 300, 220);

        facultyIdTextField.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(facultyIdTextField);
        facultyIdTextField.setBounds(130, 70, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyUpdateButtonActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_facultyUpdateButtonActionPerformed

    private void facultyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyNameTextFieldActionPerformed

    private void facultyAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyAddButtonActionPerformed
        // TODO add your handling code here:
        addRecord();
    }//GEN-LAST:event_facultyAddButtonActionPerformed
/**/
    private void facultyBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyBackButtonActionPerformed
        // TODO add your handling code here:
       dispose();
       hide();
    }//GEN-LAST:event_facultyBackButtonActionPerformed

    private void facultyClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyClearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_facultyClearButtonActionPerformed

    private void facultyDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyDeleteButtonActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_facultyDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel facultiesLabel;
    private javax.swing.JButton facultyAddButton;
    private javax.swing.JButton facultyBackButton;
    private javax.swing.JButton facultyClearButton;
    private javax.swing.JButton facultyDeleteButton;
    private javax.swing.JLabel facultyIdLabael;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JList facultyList;
    private javax.swing.JLabel facultyNameLabel;
    private javax.swing.JTextField facultyNameTextField;
    private javax.swing.JLabel facultyRemarksLabel;
    private javax.swing.JTextArea facultyRemarksTextAria;
    private javax.swing.JButton facultyUpdateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
