/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.event.*;

/**
 *
 * @author HP
 */
public class mainFrame extends javax.swing.JFrame  {
        
    Department department= new Department();
    Faculty faculty= new Faculty();
    Program program=new Program(); 
    Student student = new Student();
     Batch batch= new Batch();
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        university_of_Sindh_Label = new javax.swing.JLabel();
        AddmissionSystemLabael = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 550));
        setMinimumSize(new java.awt.Dimension(700, 570));
        getContentPane().setLayout(null);

        facultyButton.setText("FACULTY");
        facultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton);
        facultyButton.setBounds(230, 140, 210, 40);

        departmentButton.setText("DEPARTMENT");
        departmentButton.setMaximumSize(new java.awt.Dimension(65, 23));
        departmentButton.setMinimumSize(new java.awt.Dimension(65, 23));
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton);
        departmentButton.setBounds(230, 210, 210, 40);

        programButton.setText("PROGRAM");
        programButton.setMaximumSize(new java.awt.Dimension(210, 60));
        programButton.setMinimumSize(new java.awt.Dimension(210, 260));
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton);
        programButton.setBounds(230, 280, 210, 40);

        batchButton.setText("BATCH");
        batchButton.setMaximumSize(new java.awt.Dimension(210, 60));
        batchButton.setMinimumSize(new java.awt.Dimension(210, 60));
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton);
        batchButton.setBounds(230, 350, 210, 40);

        studentButton.setText("STUDENT");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton);
        studentButton.setBounds(230, 420, 210, 40);

        backButton.setText("EXIT");
        backButton.setHideActionText(true);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(270, 490, 130, 40);

        university_of_Sindh_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        university_of_Sindh_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        university_of_Sindh_Label.setText("University Of Sindh");
        getContentPane().add(university_of_Sindh_Label);
        university_of_Sindh_Label.setBounds(100, 60, 440, 34);

        AddmissionSystemLabael.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddmissionSystemLabael.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddmissionSystemLabael.setText("Addmission System");
        getContentPane().add(AddmissionSystemLabael);
        AddmissionSystemLabael.setBounds(90, 10, 450, 49);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        // TODO add your handling code here:
        if(facultyButton==evt.getSource()){
          
            faculty.show();
            
     
 }
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        if(departmentButton==evt.getSource()){
          
            department.show();
     
 }
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
        if(programButton==evt.getSource()){
            
             program.show();
        }   
    }//GEN-LAST:event_programButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
        if(batchButton==evt.getSource()){
         
          batch.show();
        }
    }//GEN-LAST:event_batchButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
      
       student.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_backButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddmissionSystemLabael;
    private javax.swing.JButton backButton;
    private javax.swing.JButton batchButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JButton programButton;
    private javax.swing.JButton studentButton;
    private javax.swing.JLabel university_of_Sindh_Label;
    // End of variables declaration//GEN-END:variables
 
}
